#!/bin/bash

function get_current_date() {
	# Get the current date and parse it into the jrnl filename format
	curDate=$(date | awk '{print $2"-"$3"-"$7}')
	curMonth=$(echo $curDate | awk -F '-' '{print $1}')
}

function check_for_dir() {
	dir_path="/home/$USER/Journal/$curMonth"
	if [[ ! -d $dir_path ]]; then
		mkdir $dir_path
	fi
}

function check_for_file() {
	file_path="$dir_path/$curDate"
	if [[ ! -f $file_path ]]; then
		touch $file_path
		echo =============================== >> $file_path
		date >> $file_path
		echo =============================== >> $file_path
		echo >> $file_path
	else
		echo =============================== >> $file_path
		date >> $file_path
		echo =============================== >> $file_path
		echo >> $file_path
	fi
}

get_current_date
check_for_dir
check_for_file
#vim $file_path
