#!/bin/bash

#ENVS
JOURNAL_DIR=${JOURNAL_DIR:-"$HOME/Journal"}
CURMONTH_DIR=${CURMONTH_DIR:-""}

function read_config_file() {
	locate_jrnl_install
	install_path=$(echo $jrnl_install_loc | awk -F '/' '{ for (i = 1; i < NF; i++) {printf $i"/"}}')
	config_file="$install_path/jrnl.config"
	readarray config_settings < <(awk -F'=' '{ chr=substr($i, 1,1); if (chr != "#") {print $1, $2}}' $config_file)
	set_config_settings
}

function set_config_settings() {
	for ((i = 0; i <= "${#config_settings[@]}"; i++)); do
		for key in ${config_settings[$i]}; do
			echo "This it the key:" $key
			setting=$(echo ${config_settings[$i]} | awk '{print $2}')

			case "$key" in
			"JOURNAL_DIR")
				printf "This is the setting for JOUNRAL_DIR: %s\n" "$setting" 
				break
			;;
			"LOGGING_DIR")
				printf "This is the setting for LOGGING_DIR: %s\n" "$setting"	
				break
			;;
			*)
				printf "Not a valid config key: %s\n" "${key}"
				break
			;;
			esac
		done
	done
}

function get_current_date() {
	# Get the current date and parse it into the jrnl filename format
	curDate=$( date | awk '{print $2"-"$3"-"$7}' )
	curMonth=$( echo $curDate | awk -F '-' '{print $1}' )
}

function check_for_dir() {
	dir_path=$1
	if [[ ! -d $dir_path ]]; then
		mkdir -p $dir_path
	fi
}

function check_for_file() {
	file_path="$CURMONTH_DIR/$curDate"
	if [[ ! -f $file_path ]]; then
		touch $file_path
	elif [ -n get_last_line_in_file ]; then
		echo >> $file_path
	fi
	# Inserts the first entry header after file creation
	echo =============================== >> $file_path
	date >> $file_path
	echo =============================== >> $file_path
	echo >> $file_path
}

function get_last_line_in_file() {
	last_line=$(awk 'END{print}' $file_path)
}

function check_if_jrnl_in_path() {
	jrnl_cmd=$(which jrnl)
	if [ -n $jrnl_cmd ]; then
		locate_jrnl_install
	       	if [ ! -L "$HOME/.local/bin/jrnl" ]; then
			ln -s $jrnl_install_loc $HOME/.local/bin/jrnl
		fi 
	fi
}

function locate_jrnl_install() {
	jrnl_install_loc=$(find ~ -wholename "*/jrnl/jrnl" -not -path "*/." -type f 2> /dev/null) 
}

read_config_file
check_if_jrnl_in_path
get_current_date
check_for_dir "$JOURNAL_DIR"
CURMONTH_DIR="$JOURNAL_DIR/$curMonth"
check_for_dir "$CURMONTH_DIR"
check_for_file
#vim $file_path
